### ISSUE TITLE
Consider adding link to brOscat lib to the wiki

### ISSUE THREAD

**Issue by tkucic** [tpo/unofficial-as-tips#1]
I have started porting the Oscat lib to the B&R platform. It would be great to get some contributors to it.
It also contains a [quirks](https://github.com/tkucic/brOscatLib/blob/main/quirks.md) file where observed weirdness/bugs/features are logged.

[brOscat](https://github.com/tkucic/brOscatLib)

**Comment by tpo** [comment]
Hi Toni!

As you can see there hasn't been any action in the unofficial-as-tips repo for a while. I was working on an AS related project a long time ago and then moved on.

I've added you to the repository, you should have received an invite. So if you want to add things to the wiki then you should be able to do it now.

At the time when I was working on the project it seemed like the embedded/automation industry existed in a completely separate universe, where they had never even heard about a concept named open source or current dev best practices and tools. So thanks a lot for your contributions: the embedded/automation world can only get better from such intiatives as yours!
